### ISSUE TITLE
[HELLO WORLD] hello world in flutter

### ISSUE THREAD

**Issue by SaicharanKandukuri** [RandomCoderOrg/Hello-world-fever#43]
Requirements:
- Need to be beautiful
- Definitely not just plain text

> **NOTICE**: This is only for beginners who are entering to OSS and trying to participating in hacktoberfest

**Comment by coderaman7** [comment]
Hey I want this

So the requirement is that create a Hello world without just a random plain hello world text??

**Comment by RockingRishav** [comment]
Hey @SaicharanKandukuri,
I want to be assigned for this issue.Please assign this to me

**Comment by RockingRishav** [comment]
Can you please tell which Files to include in this like only the dart one or some specific files so that I can make a pr.

**Comment by SaicharanKandukuri** [comment]
Wait sorry to say @RockingRishav 
we accept only on PR per user

**Comment by RockingRishav** [comment]
Oh! it's Okay.

**Comment by VodkaCranberry** [comment]
hey @SaicharanKandukuri  I've fixed the issue 
Kindly have a look on it
If any changes are required, please let me know
