### ISSUE TITLE
[ HELLO WORLD ] In jetpack compose

### ISSUE THREAD

**Issue by SaicharanKandukuri** [RandomCoderOrg/Hello-world-fever#44]
Need a beautiful HelloWorld written with jetpack compose

> **NOTICE**: This is only for beginners who are entering to OSS and trying to participating in hacktoberfest

**Comment by RockingRishav** [comment]
I want to work upon this issue but i am not getting where to add the code , like you have so many directories but i can't find one related to jetpack compose, can you tell is it the kotlin directory for adding the code in jetpack compose?

**Comment by SaicharanKandukuri** [comment]
Just create the folder `Jetpack Compose` and add your code in it!

![image](https://user-images.githubusercontent.com/68287637/192443602-9eb0a893-c2d9-46ab-b1dd-7244d7efca09.png)

> By the way don't do PR now cause they won't be considered for Hacktober fest Until OCT 1

**Comment by RockingRishav** [comment]
Please assign me this issue and also tell if I have to add whole jetpack compose app or just the Kotlin File of the compose app?

**Comment by SaicharanKandukuri** [comment]
Just Kotlin files with correct files structure are acceptable

> You can use `.gitignore` template for kotlin from [:here:](https://github.com/JetBrains/kotlin/blob/master/.gitignore)
